services:
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 5432:5432
