services:
  httpserver:
    container_name: http-server
    build:
      context: ./build/httpserver
      dockerfile: Dockerfile
    ports:
      - 1323:1323
    volumes:
      - .:/httpserver
    env_file:
      - ./server/.env
    depends_on:
      - postgres
  wsserver:
    container_name: websocket-server
    build:
      context: ./build/wsserver
      dockerfile: Dockerfile
    ports:
      - 4649:4649
    volumes:
      - .:/wsserver
    env_file:
      - ./server/.env
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.12
    ports:
      - 8888:80
    volumes:
      - ./build/pgadmin.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres
