openapi: 3.0.1
info:
  title: sns-app
  description: ''
  version: 1.0.0
tags: []
paths:
  /authorize/refresh:
    post:
      summary: 認証トークンを更新
      deprecated: false
      description: ''
      operationId: refreshAuthorization
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data: &ref_0
                    description: データ
                    $ref: '#/components/schemas/Authorization'
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
  /authorize/line:
    post:
      summary: LINE でログイン
      deprecated: false
      description: ''
      operationId: authorizeWithLine
      tags: []
      parameters:
        - name: code
          in: query
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data: *ref_0
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
  /users/{user_id}:
    get:
      summary: ユーザーを取得する
      deprecated: false
      description: ''
      operationId: getUserById
      tags: []
      parameters:
        - name: user_id
          in: path
          description: ''
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data: &ref_1
                    $ref: '#/components/schemas/User'
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
  /users/{user_id}/update:
    get:
      summary: ユーザーを更新する
      deprecated: false
      description: ''
      operationId: updateUser
      tags: []
      parameters:
        - name: user_id
          in: path
          description: ''
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                display_name:
                  type: string
                avatar_url:
                  type: string
                cover_url:
                  type: string
                biography:
                  type: string
                birthdate:
                  type: string
                  format: date-time
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data: *ref_1
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
  /posts/create:
    post:
      summary: 投稿を作成する
      deprecated: false
      description: ''
      operationId: createPost
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data: &ref_2
                    $ref: '#/components/schemas/Post'
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
  /timeline:
    get:
      summary: タイムラインを取得する
      deprecated: false
      description: ''
      operationId: getTimeline
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: 正常に処理を終了したかどうか
                  code:
                    type: integer
                    description: レスポンスコード
                  data:
                    description: データ
                    $ref: '#/components/schemas/Timeline'
                required:
                  - ok
                  - code
                  - data
          headers: {}
      security: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: ID番号
          format: uuid
        username:
          type: string
          description: 名前
        display_name:
          type: string
        avatar_url:
          type: string
        cover_url:
          type: string
        biography:
          type: string
        birthdate:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - username
        - display_name
        - avatar_url
        - cover_url
        - biography
        - birthdate
        - updated_at
        - created_at
    Authorization:
      type: object
      properties:
        user_id:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        is_new:
          type: boolean
      required:
        - user_id
        - access_token
        - refresh_token
        - is_new
    Post:
      type: object
      properties:
        id:
          type: string
          description: ID番号
          format: uuid
        author: *ref_1
        content:
          type: string
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - author
        - updated_at
        - created_at
    Timeline:
      type: object
      properties:
        posts:
          type: array
          items: *ref_2
      required:
        - posts
    Response:
      title: ''
      type: object
      properties:
        ok:
          type: boolean
          description: 正常に処理を終了したかどうか
        code:
          type: integer
          description: レスポンスコード
        data:
          type: object
          properties: {}
          description: データ
      required:
        - ok
        - code
        - data
  securitySchemes: {}
servers: []
